### ISSUE TITLE
tp link tdw8961n v3

### ISSUE THREAD

**Issue by Chipsum** [dev-zzo/router-tools#8]
```
Object: 'HTPCode ' at BFC20C00, size 00008000 (ROMBIN, 4)
-> ZyNOS ROMIO header found, version string: HTP_TC V 0.05.
-> Data is compressed, compressed/original length: 000041CF/00010488.
-> Compression method: LZMA (3 zeros prepended)
Traceback (most recent call last):
  File "zynos.py", line 530, in <module>
    args.do(args)
  File "zynos.py", line 293, in do_unpack
    data = df(data)
  File "zynos.py", line 18, in decompress_lzma
    p = subprocess.Popen(['lzma', '-d'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=False)
  File "C:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by Chipsum** [comment]
it is installed, forget about it not working anyway.
